services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/local/db/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:-3306}:3306

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data

  app-local:
    build:
      context: .
      dockerfile: ./docker/local/app/Dockerfile
    restart: unless-stopped
    command: sleep infinity
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - ${APP_LOCAL_PORT:-3000}:3000
    depends_on:
      - db
      - redis

  app-runtime:
    build:
      context: .
      dockerfile: ./docker/runtime/app/Dockerfile
      target: runner
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MEDIA_ROOT: ${MEDIA_ROOT}
      REDIS_URL: ${REDIS_URL}
      NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
      NEXT_PUBLIC_WEB_UI_URL: ${NEXT_PUBLIC_WEB_UI_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - ${APP_RUNTIME_PORT:-3001}:3000
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: ./docker/runtime/app/Dockerfile
      target: worker
    restart: unless-stopped
    environment:
      MEDIA_ROOT: ${MEDIA_ROOT}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    depends_on:
      - redis

  migration:
    build:
      context: .
      dockerfile: ./docker/runtime/app/Dockerfile
      target: migration
    restart: no
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}
    depends_on:
      - db

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - ${CADDY_HTTP_PORT:-80}:80
      - ${CADDY_HTTPS_PORT:-443}:443
      - ${CADDY_HTTPS_PORT:-443}:443/udp # HTTP/3（QUIC）用
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data # SSL証明書などを保存
      - caddy_config:/config # Caddyの設定を保存
    environment:
      - ACME_AGREE=true e # Let's Encryptの利用規約に自動同意
    depends_on:
      - app
    profiles:
      - public

volumes:
  db_data:
  redis_data:
  caddy_data:
