export const statements = [
  "archive:extract",
  "favorite:update",
  "favorite:update-multiple",
  "favorite:delete",
  "favorite:delete-multiple",
  "favorite:revalidate",
  "favorite:revalidate-multiple",
  "file:rename",
  "file:move",
  "file:copy",
  "file:delete",
  "file:restore",
  "folder:rename",
  "folder:move",
  "folder:copy",
  "folder:delete",
  "folder:restore",
  "folder:update-history",
  "folder:list",
  "folder:list-history",
  "folder:pin-history",
  "folder:create",
  "thumbnail:create",
  "tag:create",
  "tag:delete",
  "db-backup:dump",
  "db-backup:restore",
  "db-backup:list",
  "db-backup:delete",
  "db-backup:clean",
  "db-backup:upload",
  "db-backup:download",
] as const;

export type Statement = (typeof statements)[number];
