export type AppErrorCode =
  | "AUTH_REQUIRED"
  | "FILE_NOT_FOUND"
  | "MISSING_REQUIRED_PARAMETER"
  | "MISSING_REQUIRED_DATA"
  | "INVALID_REQUEST_PARAMETER"
  | "INVALID_REQUEST_DATA"
  | "INVALID_FILE_NAME";
